---
- hosts: all
  connection: local
  tasks:
  - name:
      "set the cron schedule to pull recipe data"
    cron:
      name: "pull recipe data"
      hour: 5
      minute: 55
      user: root
      job: "/opt/recipe-linebot/bin/recipe-linebot -m pullbatch -c /ope/recipe-linebot/etc/recipe-linebot.json 1>> /var/log/recipe-linebot/pullbatch-output.log 2>> /var/log/recipe-linebot/pullbatch-error.log"
      cron_file: recipe-linebot.cron
